'use strict';

/**
 * slide-jy-diff.js — task 41.5 deliverable.
 *
 * Compare sample/slide-jy.js against module 76 in sample/t_captcha_slide.js
 * and emit a short markdown verdict at
 *   output/captcha-orchestrator/slide-jy-diff.md
 *
 * This is a one-shot classification ("is the ajax layer in module 76 the
 * same library that /slide-jy.js ships, or something different?"). We
 * answer by probing for distinctive library markers: jQuery-only tokens
 * (jQuery.fn.init, noConflict, Sizzle, version literal), Zepto-only tokens
 * (Zepto/zepto literal, ajaxJSONP), shared shape (camelCase, ajaxSettings,
 * extend count). Sizes and SHA-256 content hashes are also reported so the
 * reader can see at a glance that the two blobs are not byte-equivalent.
 *
 * Idempotent: running twice produces a byte-identical diff doc.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');
const BUNDLE = path.join(ROOT, 'sample', 't_captcha_slide.js');
const SLIDE_JY = path.join(ROOT, 'sample', 'slide-jy.js');
const MODULES_JSON = path.join(ROOT, 'output', 'captcha-orchestrator', 'modules.json');
const OUT = path.join(ROOT, 'output', 'captcha-orchestrator', 'slide-jy-diff.md');

function probes(text) {
  return {
    'jQuery.fn.init': /jQuery\.fn\.init/.test(text),
    'Sizzle': /Sizzle/.test(text),
    'noConflict': /noConflict/.test(text),
    'jquery 1.11.3 literal': /1\.11\.3/.test(text),
    'Zepto literal': /Zepto/.test(text),
    'zepto literal (case-insensitive)': /zepto/i.test(text),
    'camelCase': /camelCase/.test(text),
    'ajaxSettings': /ajaxSettings/.test(text),
    'ajaxJSONP': /ajaxJSONP/.test(text),
    '__esModule': /__esModule/.test(text),
    'extend occurrences': (text.match(/extend/g) || []).length,
    'css occurrences': (text.match(/\.css\b/g) || []).length
  };
}

function sha256(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

function main() {
  const bundleSrc = fs.readFileSync(BUNDLE, 'utf8');
  const modules = JSON.parse(fs.readFileSync(MODULES_JSON, 'utf8'));
  const mod76 = modules.find((m) => m.id === 76);
  if (!mod76) throw new Error('module 76 not found');
  const mod76Src = bundleSrc.slice(mod76.sourceRange[0], mod76.sourceRange[1]);
  const slideJy = fs.readFileSync(SLIDE_JY, 'utf8');

  const mod76Probes = probes(mod76Src);
  const slideProbes = probes(slideJy);

  const lines = [];
  lines.push('# slide-jy.js vs module 76 — library classification');
  lines.push('');
  lines.push('Generated by `research/captcha-orchestrator/slide-jy-diff.js` (task 41.5).');
  lines.push('');
  lines.push('## Inputs');
  lines.push('');
  lines.push('| file | bytes | sha256 |');
  lines.push('|------|------:|--------|');
  lines.push('| `sample/t_captcha_slide.js` module 76 (source range ' +
    '`[' + mod76.sourceRange[0] + ', ' + mod76.sourceRange[1] + ')`) | ' + mod76Src.length +
    ' | `' + sha256(mod76Src) + '` |');
  lines.push('| `sample/slide-jy.js` (full file)                    | ' +
    slideJy.length + ' | `' + sha256(slideJy) + '` |');
  lines.push('');
  lines.push('Module 76 is the `jquery-like` webpack module flagged in the task 41.4');
  lines.push('structural survey as owning `ajax`, `ajaxJSONP`, `Event`, and ~43 other');
  lines.push('exports. `sample/slide-jy.js` is the external script the orchestrator');
  lines.push('fetches via `getScript({src: htdocsPath + "/slide-jy.js", ...})` in');
  lines.push('module 64 when the user agent is not mobile.');
  lines.push('');
  lines.push('## Distinctive-marker probe');
  lines.push('');
  lines.push('| marker | module 76 | slide-jy.js |');
  lines.push('|--------|-----------|-------------|');
  for (const k of Object.keys(mod76Probes)) {
    lines.push('| ' + k + ' | ' + JSON.stringify(mod76Probes[k]) + ' | ' + JSON.stringify(slideProbes[k]) + ' |');
  }
  lines.push('');
  lines.push('## Version literals');
  lines.push('');
  const slideVers = slideJy.match(/["']([0-9]+\.[0-9]+\.[0-9]+)["']/g) || [];
  const mod76Vers = mod76Src.match(/["']([0-9]+\.[0-9]+\.[0-9]+)["']/g) || [];
  lines.push('- `slide-jy.js` version literals: `' + (slideVers.slice(0, 5).join(', ') || '(none)') + '`');
  lines.push('- module 76 version literals: `' + (mod76Vers.slice(0, 5).join(', ') || '(none)') + '`');
  lines.push('');
  lines.push('## Verdict');
  lines.push('');
  lines.push('**Module 76 and `slide-jy.js` are different libraries.**');
  lines.push('');
  lines.push('- `slide-jy.js` is jQuery 1.11.3 (96,410 bytes). Evidence: explicit');
  lines.push('  `"1.11.3"` version literal; `noConflict` global-export footer;');
  lines.push('  ~47 `extend` occurrences (jQuery spreads `$.extend` liberally); no');
  lines.push('  `Zepto` / `ajaxJSONP` tokens.');
  lines.push('- Module 76 is Zepto (27,825 bytes, embedded as a webpack module).');
  lines.push('  Evidence: explicit `Zepto` literal; exports `ajaxJSONP` (a Zepto-only');
  lines.push('  ajax method — jQuery 1.x uses `jsonp` via `$.ajax({dataType:"jsonp"})`');
  lines.push('  instead); no `jQuery.fn.init` / `Sizzle` / `noConflict`; only ~3');
  lines.push('  `extend` occurrences, consistent with Zepto\'s slimmer surface.');
  lines.push('');
  lines.push('The two files therefore play the same role (`window.$`) but are');
  lines.push('alternatives, not the same library. Module 64 picks between them at');
  lines.push('load time: on mobile user-agents it does `window.$ = n(76)` (inline');
  lines.push('Zepto); otherwise it fetches `/slide-jy.js` via `getScript` and waits');
  lines.push('for `window.$` to be assigned by that script (jQuery).');
  lines.push('');

  fs.writeFileSync(OUT, lines.join('\n'));
  process.stdout.write('slide-jy-diff: wrote ' + OUT + '\n');
}

if (require.main === module) {
  main();
}

module.exports = { main };
